### PR TITLE
Fix AppStream metadata problems

### PR DESCRIPTION
**Pull request by Mailaender**
Adds https://hughsie.github.io/oars/ and fixes https://freedesktop.org/software/appstream/docs/chap-Metadata.html compatiblity problems

Required for @flathub inclusion.

### CODE REVIEW

**Comment by onpon4** [comment]
Oh, thanks, much appreciated!

🦇

**Review by onpon4 — COMMENTED** [review]
Hey, just a followup, I noticed that removing the icon tag causes a failure with desktop entry generation. Could you clarify what this change is for exactly? https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-icon lists the <icon> tag as a valid tag, so does the restriction come from flathub?

🦇

**Comment by Mailaender** [comment]
They `flatpak run --env=G_DEBUG=fatal-criticals org.freedesktop.appstream-glib validate io.github.naikari.Naikari.appdata.xml` which spits out warnings and errors. I think you used a stock icon (like from an icon theme) when it didn't exist for Naikari. I am not really sure what this tag does. It seems redundant to the `.desktop` file to me.

**Comment by onpon4** [comment]
Hm, well Naikari does actually install the icon listed there when you do `meson install`, and removing the stock icon definition causes this error when attempting to build with `meson compile` (apparently it's required for `make-desktop-file` to work):

```
FAILED: io.github.naikari.Naikari.desktop 
/usr/bin/appstreamcli make-desktop-file ../io.github.naikari.Naikari.metainfo.xml io.github.naikari.Naikari.desktop
Augmenting existing desktop-entry file 'io.github.naikari.Naikari.desktop' with data from 'io.github.naikari.Naikari.metainfo.xml'.
No stock icon name was provided in the metainfo file. Can not continue.
```

Previously the icon was defined as "naikari", but I recently copied a change that Naev made last year, changing the name of the icon as installed on the system to Naikari's RTLD (bd0fb39). Does that help any? Alternatively, does the flatpak system need some extra configuration, perhaps? It seems there must be a way to keep `.desktop` file generation with `make-desktop-file` while still being OK for flatpak (and for what it's worth Naev still has the icon definition in its metainfo and I think someone maintains a flatpak of that project).

Regarding seeming redundant to the `.desktop` file, I did some looking into it and that `.desktop` file actually isn't used unless `appstreamcli` is unavailable, I assume as a fallback.

By the way, I apologize for not speaking with very much knowledge on the subject. I didn't have much involvement in the creation of Naev's meson build system and also have no experience with flatpak packaging, so this is a little bit of a learning experience. 😅

🦇

**Comment by Mailaender** [comment]
Meson might have been designed for GNOME applications that use generic icons from the theme and you copy pasted a template from there. I have never seen games use that tag and I have never seen a .desktop file being generated from appdata. You should probably avoid `make-desktop-file` as it requires a stock icon which you don't have.

**Comment by eli-schwartz** [comment]
Genuinely curious, what's the point of autogenerating a .desktop file at build time when there's already -- an apparently better -- one checked into git?

**Comment by onpon4** [comment]
Well I wasn't involved in that (it's a decision inherited from the Naev project, commit where it was introduced was 8c19a2a) so I can't say for sure why that particular change was made. It could have just been an error of judgment for all I know.

It looks like getting rid of this would be an easy and probably non-destructive change, so I think I'll do that. Now that I understand what's going on better, I'd have to agree that it seems unnecessary.

🦇

**Pull request merged**
